# -*- coding: utf-8 -*-

JORDAN_CITIES = [
    ('amman', 'Amman'),
    ('zarqa', 'Zarqa'),
    ('irbid', 'Irbid'),
    ('aqaba', 'Aqaba'),
    ('salt', 'Salt'),
    ('madaba', 'Madaba'),
    ('mafraq', 'Mafraq'),
    ('karak', 'Karak'),
    ('tafilah', 'Tafilah'),
    ('maan', "Ma'an"),
    ('jerash', 'Jerash'),
    ('ajloun', 'Ajloun'),
    ('ramtha', 'Ramtha'),
    ('russeifa', 'Russeifa'),
    ('sahab', 'Sahab'),
    ('jubeiha', 'Jubeiha'),
    ('abdoun', 'Abdoun'),
    ('marj_al_hamam', 'Marj Al Hamam'),
    ('fuheis', 'Fuheis'),
    ('sweileh', 'Sweileh'),
    ('wadi_musa', 'Wadi Musa (Petra)'),
    ('ghour_safi', 'Ghor Safi'),
    ('dead_sea', 'Dead Sea'),
    ('petra', 'Petra'),
    ('wadi_rum', 'Wadi Rum'),
    ('al_husn', 'Al Husn'),
    ('kufranja', 'Kufranja'),
    ('sarih', 'Sarih'),
    ('anjarah', 'Anjarah'),
    ('balqa', 'Balqa'),
    ('dhiban', 'Dhiban'),
    ('muwaqqar', 'Muwaqqar'),
    ('naour', 'Naour'),
    ('quwaysimah', 'Quwaysimah'),
    ('taybeh', 'Taybeh'),
    ('umm_qais', 'Umm Qais'),
    ('other', 'Other'),
]

JORDAN_CITIES_AR = [
    ('amman', 'عمان'),
    ('zarqa', 'الزرقاء'),
    ('irbid', 'إربد'),
    ('aqaba', 'العقبة'),
    ('salt', 'السلط'),
    ('madaba', 'مادبا'),
    ('mafraq', 'المفرق'),
    ('karak', 'الكرك'),
    ('tafilah', 'الطفيلة'),
    ('maan', 'معان'),
    ('jerash', 'جرش'),
    ('ajloun', 'عجلون'),
    ('ramtha', 'الرمثا'),
    ('russeifa', 'الرصيفة'),
    ('sahab', 'سحاب'),
    ('jubeiha', 'الجبيهة'),
    ('abdoun', 'عبدون'),
    ('marj_al_hamam', 'مرج الحمام'),
    ('fuheis', 'الفحيص'),
    ('sweileh', 'صويلح'),
    ('wadi_musa', 'وادي موسى (البتراء)'),
    ('ghour_safi', 'غور الصافي'),
    ('dead_sea', 'البحر الميت'),
    ('petra', 'البتراء'),
    ('wadi_rum', 'وادي رم'),
    ('al_husn', 'الحصن'),
    ('kufranja', 'كفرنجة'),
    ('sarih', 'صريح'),
    ('anjarah', 'عنجرة'),
    ('balqa', 'البلقاء'),
    ('dhiban', 'ذيبان'),
    ('muwaqqar', 'الموقر'),
    ('naour', 'ناعور'),
    ('quwaysimah', 'القويسمة'),
    ('taybeh', 'الطيبة'),
    ('umm_qais', 'أم قيس'),
    ('other', 'أخرى'),
]

UI_STRINGS = {
    'en': {
        'nav_home': 'Home',
        'nav_about': 'About',
        'nav_all_in': 'All in',
        'nav_cart': 'Cart',
        'footer_tagline': 'Industrial tools across Jordan. Cash on delivery.',
        'footer_pages': 'Pages',
        'footer_order': 'Order',
        'footer_call': 'Call us',
        'footer_products': 'Products',
        'footer_checkout': 'Checkout',
        'hero_label': 'Industrial Tools · Jordan',
        'hero_title_1': 'Industrial Tools',
        'hero_title_2': 'Delivered Fast',
        'hero_lead': 'Real stock · Cash on delivery · 36+ cities nationwide',
        'shop_now': 'Shop Now',
        'call_us': 'Call Us',
        'cod_title': 'Cash on Delivery',
        'cod_sub': 'Pay at your door',
        'inventory_title': 'Real Inventory',
        'inventory_sub': 'Stock-backed',
        'delivery_title': 'Fast Delivery',
        'delivery_sub': 'All Jordan',
        'shop_by_category': 'Shop by Category',
        'view_all': 'View all',
        'items': 'items',
        'featured': 'Featured Products',
        'cta_title': 'Need tools today?',
        'cta_lead': 'Order online — we call you, then deliver.',
        'start_shopping': 'Start Shopping',
        'about_title': 'About Torque Zone',
        'about_sub': 'Trusted industrial tools in Jordan',
        'about_h2': 'Built for professionals',
        'about_p': 'Quality tools, fair prices, cash on delivery. Every order confirmed by phone.',
        'browse_shop': 'Browse Shop',
        'feat_trust': 'Trust',
        'feat_trust_p': 'Real inventory only',
        'feat_service': 'Service',
        'feat_service_p': 'Phone confirmation',
        'feat_delivery': 'Delivery',
        'feat_delivery_p': 'Nationwide COD',
        'shop_label': 'Shop',
        'shop_title': 'Shop',
        'shop_lead': 'Browse products · Add to cart · Pay on delivery',
        'search_ph': 'Search products…',
        'sort_name': 'Name A–Z',
        'sort_price_asc': 'Price: Low to High',
        'sort_price_desc': 'Price: High to Low',
        'apply': 'Apply',
        'all': 'All',
        'products_count': 'products',
        'cod': 'Cash on Delivery',
        'no_products': 'No products found',
        'prev': '← Prev',
        'next': 'Next →',
        'add_to_cart': '+ Add to Cart',
        'adding': 'Adding…',
        'back_shop': '← Back to shop',
        'quantity': 'Quantity',
        'description': 'Description',
        'in_stock': '✓ In stock',
        'related': 'Related Products',
        'your_cart': 'Your Cart',
        'order_summary': 'Order Summary',
        'subtotal': 'Subtotal',
        'payment': 'Payment',
        'checkout': 'Checkout →',
        'continue_shopping': 'Continue Shopping',
        'cart_empty': 'Your cart is empty',
        'cart_empty_p': 'Browse our shop and add tools to get started.',
        'checkout_title': 'Checkout',
        'delivery_details': 'Delivery Details',
        'full_name': 'Full Name *',
        'phone': 'Phone Number *',
        'address': 'Delivery Address *',
        'address_ph': 'Street, building, area…',
        'city': 'City *',
        'city_ph': 'Select your city',
        'place_order': 'Place Order',
        'your_order': 'Your Order',
        'total': 'Total',
        'pay_hint': '💵 Pay cash when your order arrives',
        'order_placed': 'Order Placed!',
        'order_confirm_call': "We'll call",
        'order_confirm_to': 'to confirm.',
        'pay_on_arrival': 'Pay cash when your order arrives',
        'back_home': 'Back to Home',
        'flow_shop': '① Shop',
        'flow_cart': '② Cart',
        'flow_checkout': '③ Checkout',
        'flow_done': '④ Done',
        'remove': 'Remove',
        'decrease': 'Decrease',
        'increase': 'Increase',
        'menu': 'Menu',
        'err_name': 'Please enter your name.',
        'err_phone': 'Please enter your phone number.',
        'err_address': 'Please enter your delivery address.',
        'err_city': 'Please select your city.',
        'out_of_stock': 'Out of stock',
        'stock_left': 'Only %s left in stock',
        'max_qty_reached': 'Maximum available quantity reached',
    },
    'ar': {
        'nav_home': 'الرئيسية',
        'nav_about': 'من نحن',
        'nav_all_in': 'الكل في',
        'nav_cart': 'السلة',
        'footer_tagline': 'عدد صناعية — أدوات صناعية في الأردن. الدفع عند الاستلام.',
        'footer_pages': 'الصفحات',
        'footer_order': 'الطلب',
        'footer_call': 'اتصل بنا',
        'footer_products': 'المنتجات',
        'footer_checkout': 'إتمام الطلب',
        'hero_label': 'عدد صناعية · الأردن',
        'hero_title_1': 'أدوات صناعية',
        'hero_title_2': 'توصيل لبابك',
        'hero_lead': 'مخزون حقيقي · دفع عند الاستلام · أكثر من 36 مدينة',
        'shop_now': 'تسوق الآن',
        'call_us': 'اتصل بنا',
        'cod_title': 'الدفع عند الاستلام',
        'cod_sub': 'ادفع عند بابك',
        'inventory_title': 'مخزون حقيقي',
        'inventory_sub': 'متوفر فعلياً',
        'delivery_title': 'توصيل سريع',
        'delivery_sub': 'كل الأردن',
        'shop_by_category': 'تسوق حسب الفئة',
        'view_all': 'عرض الكل',
        'items': 'منتج',
        'featured': 'منتجات مميزة',
        'cta_title': 'تحتاج أدوات اليوم؟',
        'cta_lead': 'اطلب أونلاين — نتصل بك ثم نوصل الطلب.',
        'start_shopping': 'ابدأ التسوق',
        'about_title': 'عن تورك زون',
        'about_sub': 'عدد صناعية — أدوات صناعية موثوقة في الأردن',
        'about_h2': 'صُممت للمحترفين',
        'about_p': 'أدوات بجودة عالية، أسعار عادلة، والدفع عند الاستلام. كل طلب يُؤكد هاتفياً.',
        'browse_shop': 'تصفح المتجر',
        'feat_trust': 'ثقة',
        'feat_trust_p': 'مخزون حقيقي فقط',
        'feat_service': 'خدمة',
        'feat_service_p': 'تأكيد هاتفي',
        'feat_delivery': 'توصيل',
        'feat_delivery_p': 'دفع عند الاستلام',
        'shop_label': 'المتجر',
        'shop_title': 'المتجر',
        'shop_lead': 'تصفح المنتجات · أضف للسلة · ادفع عند الاستلام',
        'search_ph': 'ابحث عن منتج…',
        'sort_name': 'الاسم أ–ي',
        'sort_price_asc': 'السعر: من الأقل للأعلى',
        'sort_price_desc': 'السعر: من الأعلى للأقل',
        'apply': 'تطبيق',
        'all': 'الكل',
        'products_count': 'منتج',
        'cod': 'الدفع عند الاستلام',
        'no_products': 'لا توجد منتجات',
        'prev': '→ السابق',
        'next': 'التالي ←',
        'add_to_cart': '+ أضف للسلة',
        'adding': 'جاري الإضافة…',
        'back_shop': '→ العودة للمتجر',
        'quantity': 'الكمية',
        'description': 'الوصف',
        'in_stock': '✓ متوفر',
        'related': 'منتجات ذات صلة',
        'your_cart': 'سلتك',
        'order_summary': 'ملخص الطلب',
        'subtotal': 'المجموع الفرعي',
        'payment': 'الدفع',
        'checkout': 'إتمام الطلب ←',
        'continue_shopping': 'متابعة التسوق',
        'cart_empty': 'سلتك فارغة',
        'cart_empty_p': 'تصفح المتجر وأضف الأدوات التي تحتاجها.',
        'checkout_title': 'إتمام الطلب',
        'delivery_details': 'بيانات التوصيل',
        'full_name': 'الاسم الكامل *',
        'phone': 'رقم الهاتف *',
        'address': 'عنوان التوصيل *',
        'address_ph': 'الشارع، المبنى، المنطقة…',
        'city': 'المدينة *',
        'city_ph': 'اختر مدينتك',
        'place_order': 'تأكيد الطلب',
        'your_order': 'طلبك',
        'total': 'الإجمالي',
        'pay_hint': '💵 ادفع نقداً عند استلام الطلب',
        'order_placed': 'تم تقديم الطلب!',
        'order_confirm_call': 'سنتصل على',
        'order_confirm_to': 'للتأكيد.',
        'pay_on_arrival': 'ادفع نقداً عند استلام الطلب',
        'back_home': 'العودة للرئيسية',
        'flow_shop': '① المتجر',
        'flow_cart': '② السلة',
        'flow_checkout': '③ الدفع',
        'flow_done': '④ تم',
        'remove': 'إزالة',
        'decrease': 'تقليل',
        'increase': 'زيادة',
        'menu': 'القائمة',
        'err_name': 'يرجى إدخال اسمك.',
        'err_phone': 'يرجى إدخال رقم هاتفك.',
        'err_address': 'يرجى إدخال عنوان التوصيل.',
        'err_city': 'يرجى اختيار مدينتك.',
        'out_of_stock': 'غير متوفر',
        'stock_left': 'متبقي %s فقط',
        'max_qty_reached': 'وصلت للحد الأقصى المتاح',
    },
}

DELIVERY_STATUSES = [
    ('pending', 'Pending'),
    ('confirmed', 'Confirmed'),
    ('preparing', 'Preparing'),
    ('out_for_delivery', 'Out for Delivery'),
    ('delivered', 'Delivered'),
    ('cancelled', 'Cancelled'),
]
