# -*- coding: utf-8 -*-

JORDAN_CITIES = [
    ('amman', 'Amman'),
    ('zarqa', 'Zarqa'),
    ('irbid', 'Irbid'),
    ('aqaba', 'Aqaba'),
    ('salt', 'Salt'),
    ('madaba', 'Madaba'),
    ('mafraq', 'Mafraq'),
    ('karak', 'Karak'),
    ('tafilah', 'Tafilah'),
    ('maan', "Ma'an"),
    ('jerash', 'Jerash'),
    ('ajloun', 'Ajloun'),
    ('ramtha', 'Ramtha'),
    ('russeifa', 'Russeifa'),
    ('sahab', 'Sahab'),
    ('jubeiha', 'Jubeiha'),
    ('abdoun', 'Abdoun'),
    ('marj_al_hamam', 'Marj Al Hamam'),
    ('fuheis', 'Fuheis'),
    ('sweileh', 'Sweileh'),
    ('wadi_musa', 'Wadi Musa (Petra)'),
    ('ghour_safi', 'Ghor Safi'),
    ('dead_sea', 'Dead Sea'),
    ('petra', 'Petra'),
    ('wadi_rum', 'Wadi Rum'),
    ('al_husn', 'Al Husn'),
    ('kufranja', 'Kufranja'),
    ('sarih', 'Sarih'),
    ('anjarah', 'Anjarah'),
    ('balqa', 'Balqa'),
    ('dhiban', 'Dhiban'),
    ('muwaqqar', 'Muwaqqar'),
    ('naour', 'Naour'),
    ('quwaysimah', 'Quwaysimah'),
    ('taybeh', 'Taybeh'),
    ('umm_qais', 'Umm Qais'),
    ('other', 'Other'),
]

JORDAN_CITIES_AR = [
    ('amman', 'عمان'),
    ('zarqa', 'الزرقاء'),
    ('irbid', 'إربد'),
    ('aqaba', 'العقبة'),
    ('salt', 'السلط'),
    ('madaba', 'مادبا'),
    ('mafraq', 'المفرق'),
    ('karak', 'الكرك'),
    ('tafilah', 'الطفيلة'),
    ('maan', 'معان'),
    ('jerash', 'جرش'),
    ('ajloun', 'عجلون'),
    ('ramtha', 'الرمثا'),
    ('russeifa', 'الرصيفة'),
    ('sahab', 'سحاب'),
    ('jubeiha', 'الجبيهة'),
    ('abdoun', 'عبدون'),
    ('marj_al_hamam', 'مرج الحمام'),
    ('fuheis', 'الفحيص'),
    ('sweileh', 'صويلح'),
    ('wadi_musa', 'وادي موسى (البتراء)'),
    ('ghour_safi', 'غور الصافي'),
    ('dead_sea', 'البحر الميت'),
    ('petra', 'البتراء'),
    ('wadi_rum', 'وادي رم'),
    ('al_husn', 'الحصن'),
    ('kufranja', 'كفرنجة'),
    ('sarih', 'صريح'),
    ('anjarah', 'عنجرة'),
    ('balqa', 'البلقاء'),
    ('dhiban', 'ذيبان'),
    ('muwaqqar', 'الموقر'),
    ('naour', 'ناعور'),
    ('quwaysimah', 'القويسمة'),
    ('taybeh', 'الطيبة'),
    ('umm_qais', 'أم قيس'),
    ('other', 'أخرى'),
]

DELIVERY_STATUSES = [
    ('pending', 'Pending'),
    ('confirmed', 'Confirmed'),
    ('preparing', 'Preparing'),
    ('out_for_delivery', 'Out for Delivery'),
    ('delivered', 'Delivered'),
    ('cancelled', 'Cancelled'),
]
